In [1]:
import pandas as pd

# Data Collection

In [2]:
dataset = pd.read_csv("Movie_Collection.csv") # reading the csv values and storing in the variable dataset

In [3]:
dataset

,Marketing expense,Production expense,Multiplex coverage,Budget,Movie_length,Lead_ Actor_Rating,Lead_Actress_rating,Director_rating,Producer_rating,Critic_rating,Trailer_views,3D_available,Time_taken,Twitter_hastags,Genre,Avg_age_actors,Num_multiplex,Collection,Start_Tech_Oscar
0,20.1264,59.62,0.462,36524.125,138.7,7.825,8.095,7.910,7.995,7.94,527367,YES,109.60,223.840,Thriller,23,494,48000,1
1,20.5462,69.14,0.531,35668.655,152.4,7.505,7.650,7.440,7.470,7.44,494055,NO,146.64,243.456,Drama,42,462,43200,0
2,20.5458,69.14,0.531,39912.675,134.6,7.485,7.570,7.495,7.515,7.44,547051,NO,147.88,2022.400,Comedy,38,458,69400,1
3,20.6474,59.36,0.542,38873.890,119.3,6.895,7.035,6.920,7.020,8.26,516279,YES,185.36,225.344,Drama,45,472,66800,1
4,21.3810,59.36,0.542,39701.585,127.7,6.920,7.070,6.815,7.070,8.26,531448,NO,176.48,225.792,Drama,55,395,72400,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,21.2526,78.86,0.427,36624.115,142.6,8.680,8.775,8.620,8.970,6.80,492480,NO,186.96,243.584,Action,27,561,44800,0
502,20.9054,78.86,0.427,33996.600,150.2,8.780,8.945,8.770,8.930,7.80,482875,YES,132.24,263.296,Action,20,600,41200,0
503,21.2152,78.86,0.427,38751.680,164.5,8.830,8.970,8.855,9.010,7.80,532239,NO,109.56,243.824,Comedy,31,576,47800,0
504,22.1918,78.86,0.427,37740.670,162.8,8.730,8.845,8.800,8.845,6.80,496077,YES,158.80,303.520,Comedy,47,607,44000,0
505,20.9482,78.86,0.427,33496.650,154.3,8.640,8.880,8.680,8.790,6.80,518438,YES,205.60,203.040,Comedy,45,604,38000,0

# Data Preprocessing Starts

In [4]:
dataset.isna() #finding for any null/missing values in the data set

,Marketing expense,Production expense,Multiplex coverage,Budget,Movie_length,Lead_ Actor_Rating,Lead_Actress_rating,Director_rating,Producer_rating,Critic_rating,Trailer_views,3D_available,Time_taken,Twitter_hastags,Genre,Avg_age_actors,Num_multiplex,Collection,Start_Tech_Oscar
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
502,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
503,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
504,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
505,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [5]:
dataset.isnull().sum() #count of null/missing values column wise

Marketing expense       0
Production expense      0
Multiplex coverage      0
Budget                  0
Movie_length            0
Lead_ Actor_Rating      0
Lead_Actress_rating     0
Director_rating         0
Producer_rating         0
Critic_rating           0
Trailer_views           0
3D_available            0
Time_taken             12
Twitter_hastags         0
Genre                   0
Avg_age_actors          0
Num_multiplex           0
Collection              0
Start_Tech_Oscar        0
dtype: int64

# Thumb Rule for Machine Learning and Data Science

In [6]:
# In the dataset, there should not be any missing values/empty/nan/null values
#-------Why did the NaN value came in the dataset, is there any relationship/logic else without any reason
#-------in the placement dataset the NaN value came whenever the student is not placed.
# Once missing/empty/nan/null values are resolved, need to check for outliers

## Methods to replace missing values

In [7]:
#1) Replace the missing values with central tendancy (Mean, Median, Mode)
#2) Delete the entire row.
#3) Respective to the problem, have to replace the missing values with hard coded(standard) values. For our data set we need to replace it with 0 whic will not change the meaning or value.
#4) Consider this as a semi supervised, create a model, so that we can predict the missing values.

#For categorical data replacement
#1) Replace with mode
#2) Semi supervised - classification

#Incase of multiple columns NULL values replacement we need use "IMPUTATORS"

In [8]:
# In our dataset the NULL values are exists in the Time Taken column and also in the time taken column already 0 also exists. 
# So decided to replace the NULL values with 0 which will not impact the model creation processing. 
dataset["Time_taken"].fillna(0,inplace=True) #inplace=True means the changes directly applied into the dataset, not assigning to any variable.

In [9]:
dataset.isna().sum()

Marketing expense      0
Production expense     0
Multiplex coverage     0
Budget                 0
Movie_length           0
Lead_ Actor_Rating     0
Lead_Actress_rating    0
Director_rating        0
Producer_rating        0
Critic_rating          0
Trailer_views          0
3D_available           0
Time_taken             0
Twitter_hastags        0
Genre                  0
Avg_age_actors         0
Num_multiplex          0
Collection             0
Start_Tech_Oscar       0
dtype: int64

#  Data Science

In [10]:
# splitting the Quantitative and Qualitative Columns from the given dataset 
# Finding the Mean, Median, and Mode values for the given dataset(Measure of Central Tendency) 
# Finding IQR, 1.5rule, lesser outlier, and Greater outlier.

In [11]:
dataset.info() # displays the properties of the dataset

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 19 columns):
Marketing expense      506 non-null float64
Production expense     506 non-null float64
Multiplex coverage     506 non-null float64
Budget                 506 non-null float64
Movie_length           506 non-null float64
Lead_ Actor_Rating     506 non-null float64
Lead_Actress_rating    506 non-null float64
Director_rating        506 non-null float64
Producer_rating        506 non-null float64
Critic_rating          506 non-null float64
Trailer_views          506 non-null int64
3D_available           506 non-null object
Time_taken             506 non-null float64
Twitter_hastags        506 non-null float64
Genre                  506 non-null object
Avg_age_actors         506 non-null int64
Num_multiplex          506 non-null int64
Collection             506 non-null int64
Start_Tech_Oscar       506 non-null int64
dtypes: float64(12), int64(5), object(2)
memory usage: 75.2+ KB

In [12]:
#From the above output we can confirm below points
# There are 506 rows in the given dataset which starts 0 to 505
# There are 19 columns in the given dataset
# There are 12 float columns, 5 int column, 2 object columns
# All columns are having 506 values, but Time_Taken column has only 494 value. So Time_Taken column has 506-494 = 12 (NULL or NaN) value
# In the above statement we are doing dataset.info() after replacing the nan value with 0 thats why we are seeing 506 againist Time_Taken column
# If we use the same statement before the nan value replacement, we will see 494 as a value for the Time_Taken column.
# int = whole number , float = decimal value (continuous value) => Quantitative Column
# object = categorical value => Qualitative Column

#Splitting the Quan and Qual Columns
===================================
#Quan = ["Marketing expense","Production expense","Multiplex coverage","Budget","Movie_length","Lead_ Actor_Rating","Lead_Actress_rating","Director_rating","Producer_rating","Critic_rating","Trailer_views","Time_taken","Twitter_hastags","Avg_age_actors","Num_multiplex","Collection","Start_Tech_Oscar"]
#Qual = ["3D_available","Genre"]

In [13]:
dir(dataset) # to display all inbuild functions, from this we can use "dtypes" function for our task
# please go through all functions usage in w3 school for pandas

['Avg_age_actors',
 'Budget',
 'Collection',
 'Critic_rating',
 'Director_rating',
 'Genre',
 'Lead_Actress_rating',
 'Movie_length',
 'Num_multiplex',
 'Producer_rating',
 'Start_Tech_Oscar',
 'T',
 'Time_taken',
 'Trailer_views',
 'Twitter_hastags',
 '_AXIS_ALIASES',
 '_AXIS_IALIASES',
 '_AXIS_LEN',
 '_AXIS_NAMES',
 '_AXIS_NUMBERS',
 '_AXIS_ORDERS',
 '_AXIS_REVERSED',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_priority__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__div__',
 '__doc__',
 '__eq__',
 '__finalize__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__imod__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdiv__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rmatmul__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__round__',
 '__rpow__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__setitem__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__weakref__',
 '__xor__',
 '_accessors',
 '_add_numeric_operations',
 '_add_series_only_operations',
 '_add_series_or_dataframe_operations',
 '_agg_by_level',
 '_agg_examples_doc',
 '_agg_summary_and_see_also_doc',
 '_aggregate',
 '_aggregate_multiple_funcs',
 '_align_frame',
 '_align_series',
 '_box_col_values',
 '_box_item_values',
 '_builtin_table',
 '_check_inplace_setting',
 '_check_is_chained_assignment_possible',
 '_check_label_or_level_ambiguity',
 '_check_percentile',
 '_check_setitem_copy',
 '_clear_item_cache',
 '_clip_with_one_bound',
 '_clip_with_scalar',
 '_combine_const',
 '_combine_frame',
 '_combine_match_columns',
 '_combine_match_index',
 '_consolidate',
 '_consolidate_inplace',
 '_construct_axes_dict',
 '_construct_axes_dict_from',
 '_construct_axes_from_arguments',
 '_constructor',
 '_constructor_expanddim',
 '_constructor_sliced',
 '_convert',
 '_count_level',
 '_create_indexer',
 '_cython_table',
 '_data',
 '_deprecations',
 '_dir_additions',
 '_dir_deletions',
 '_drop_axis',
 '_drop_labels_or_levels',
 '_ensure_valid_index',
 '_find_valid_index',
 '_from_arrays',
 '_from_axes',
 '_get_agg_axis',
 '_get_axis',
 '_get_axis_name',
 '_get_axis_number',
 '_get_axis_resolvers',
 '_get_block_manager_axis',
 '_get_bool_data',
 '_get_cacher',
 '_get_index_resolvers',
 '_get_item_cache',
 '_get_label_or_level_values',
 '_get_numeric_data',
 '_get_space_character_free_column_resolvers',
 '_get_value',
 '_get_values',
 '_getitem_bool_array',
 '_getitem_frame',
 '_getitem_multilevel',
 '_gotitem',
 '_iget_item_cache',
 '_indexed_same',
 '_info_axis',
 '_info_axis_name',
 '_info_axis_number',
 '_info_repr',
 '_init_mgr',
 '_internal_get_values',
 '_internal_names',
 '_internal_names_set',
 '_is_builtin_func',
 '_is_cached',
 '_is_copy',
 '_is_cython_func',
 '_is_datelike_mixed_type',
 '_is_homogeneous_type',
 '_is_label_or_level_reference',
 '_is_label_reference',
 '_is_level_reference',
 '_is_mixed_type',
 '_is_numeric_mixed_type',
 '_is_view',
 '_ix',
 '_ixs',
 '_join_compat',
 '_maybe_cache_changed',
 '_maybe_update_cacher',
 '_metadata',
 '_needs_reindex_multi',
 '_obj_with_exclusions',
 '_protect_consolidate',
 '_reduce',
 '_reindex_axes',
 '_reindex_columns',
 '_reindex_index',
 '_reindex_multi',
 '_reindex_with_indexers',
 '_repr_data_resource_',
 '_repr_fits_horizontal_',
 '_repr_fits_vertical_',
 '_repr_html_',
 '_repr_latex_',
 '_reset_cache',
 '_reset_cacher',
 '_sanitize_column',
 '_selected_obj',
 '_selection',
 '_selection_list',
 '_selection_name',
 '_series',
 '_set_as_cached',
 '_set_axis',
 '_set_axis_name',
 '_set_is_copy',
 '_set_item',
 '_set_value',
 '_setitem_array',
 '_setitem_frame',
 '_setitem_slice',
 '_setup_axes',
 '_shallow_copy',
 '_slice',
 '_stat_axis',
 '_stat_axis_name',
 '_stat_axis_number',
 '_to_dict_of_blocks',
 '_try_aggregate_string_function',
 '_typ',
 '_unpickle_frame_compat',
 '_unpickle_matrix_compat',
 '_update_inplace',
 '_validate_dtype',
 '_values',
 '_where',
 '_xs',
 'abs',
 'add',
 'add_prefix',
 'add_suffix',
 'agg',
 'aggregate',
 'align',
 'all',
 'any',
 'append',
 'apply',
 'applymap',
 'as_matrix',
 'asfreq',
 'asof',
 'assign',
 'astype',
 'at',
 'at_time',
 'axes',
 'between_time',
 'bfill',
 'bool',
 'boxplot',
 'clip',
 'clip_lower',
 'clip_upper',
 'columns',
 'combine',
 'combine_first',
 'compound',
 'copy',
 'corr',
 'corrwith',
 'count',
 'cov',
 'cummax',
 'cummin',
 'cumprod',
 'cumsum',
 'describe',
 'diff',
 'div',
 'divide',
 'dot',
 'drop',
 'drop_duplicates',
 'droplevel',
 'dropna',
 'dtypes',
 'duplicated',
 'empty',
 'eq',
 'equals',
 'eval',
 'ewm',
 'expanding',
 'explode',
 'ffill',
 'fillna',
 'filter',
 'first',
 'first_valid_index',
 'floordiv',
 'from_dict',
 'from_records',
 'ge',
 'get',
 'get_dtype_counts',
 'get_ftype_counts',
 'get_values',
 'groupby',
 'gt',
 'head',
 'hist',
 'iat',
 'idxmax',
 'idxmin',
 'iloc',
 'index',
 'infer_objects',
 'info',
 'insert',
 'interpolate',
 'isin',
 'isna',
 'isnull',
 'items',
 'iteritems',
 'iterrows',
 'itertuples',
 'join',
 'keys',
 'kurt',
 'kurtosis',
 'last',
 'last_valid_index',
 'le',
 'loc',
 'lookup',
 'lt',
 'mad',
 'mask',
 'max',
 'mean',
 'median',
 'melt',
 'memory_usage',
 'merge',
 'min',
 'mod',
 'mode',
 'mul',
 'multiply',
 'ndim',
 'ne',
 'nlargest',
 'notna',
 'notnull',
 'nsmallest',
 'nunique',
 'pct_change',
 'pipe',
 'pivot',
 'pivot_table',
 'plot',
 'pop',
 'pow',
 'prod',
 'product',
 'quantile',
 'query',
 'radd',
 'rank',
 'rdiv',
 'reindex',
 'reindex_like',
 'rename',
 'rename_axis',
 'reorder_levels',
 'replace',
 'resample',
 'reset_index',
 'rfloordiv',
 'rmod',
 'rmul',
 'rolling',
 'round',
 'rpow',
 'rsub',
 'rtruediv',
 'sample',
 'select_dtypes',
 'sem',
 'set_axis',
 'set_index',
 'shape',
 'shift',
 'size',
 'skew',
 'slice_shift',
 'sort_index',
 'sort_values',
 'sparse',
 'squeeze',
 'stack',
 'std',
 'style',
 'sub',
 'subtract',
 'sum',
 'swapaxes',
 'swaplevel',
 'tail',
 'take',
 'to_clipboard',
 'to_csv',
 'to_dense',
 'to_dict',
 'to_excel',
 'to_feather',
 'to_gbq',
 'to_hdf',
 'to_html',
 'to_json',
 'to_latex',
 'to_msgpack',
 'to_numpy',
 'to_parquet',
 'to_period',
 'to_pickle',
 'to_records',
 'to_sparse',
 'to_sql',
 'to_stata',
 'to_string',
 'to_timestamp',
 'to_xarray',
 'transform',
 'transpose',
 'truediv',
 'truncate',
 'tshift',
 'tz_convert',
 'tz_localize',
 'unstack',
 'update',
 'values',
 'var',
 'where',
 'xs']

In [14]:
dataset.dtypes #displaying data type for each columns against to it in the data set

Marketing expense      float64
Production expense     float64
Multiplex coverage     float64
Budget                 float64
Movie_length           float64
Lead_ Actor_Rating     float64
Lead_Actress_rating    float64
Director_rating        float64
Producer_rating        float64
Critic_rating          float64
Trailer_views            int64
3D_available            object
Time_taken             float64
Twitter_hastags        float64
Genre                   object
Avg_age_actors           int64
Num_multiplex            int64
Collection               int64
Start_Tech_Oscar         int64
dtype: object

In [15]:
dataset["3D_available"].dtypes #displaying data type for 3D_available column ie 'O' => object

dtype('O')

In [16]:
dataset["Trailer_views"].dtypes #displaying data type for Trailer_views column ie 'int64' => whole number

dtype('int64')

In [17]:
dataset["Budget"].dtypes #displaying data type for Budget column ie 'float64' => continuous decimal value

dtype('float64')

In [18]:
#Creating empty list for Quantiative and Qualitative
Qual=[]
Quan=[]

In [19]:
def quanQual(p_dataset):  #standalone function can not be used outside this notebook
    p_Qual=[]
    p_Quan=[]
    for columnName in p_dataset.columns:
        #print(columnName)
        if(p_dataset[columnName].dtypes == 'O'):
            #print("Qual")
            p_Qual.append(columnName)
        else:
            #print("Quan")
            p_Quan.append(columnName)  
    return p_Quan, p_Qual # function can return 'n' number of values

In [20]:
quanQual(dataset)

(['Marketing expense',
  'Production expense',
  'Multiplex coverage',
  'Budget',
  'Movie_length',
  'Lead_ Actor_Rating',
  'Lead_Actress_rating',
  'Director_rating',
  'Producer_rating',
  'Critic_rating',
  'Trailer_views',
  'Time_taken',
  'Twitter_hastags',
  'Avg_age_actors',
  'Num_multiplex',
  'Collection',
  'Start_Tech_Oscar'],
 ['3D_available', 'Genre'])

In [21]:
Quan, Qual=quanQual(dataset)

In [22]:
Quan

['Marketing expense',
 'Production expense',
 'Multiplex coverage',
 'Budget',
 'Movie_length',
 'Lead_ Actor_Rating',
 'Lead_Actress_rating',
 'Director_rating',
 'Producer_rating',
 'Critic_rating',
 'Trailer_views',
 'Time_taken',
 'Twitter_hastags',
 'Avg_age_actors',
 'Num_multiplex',
 'Collection',
 'Start_Tech_Oscar']

In [23]:
Qual

['3D_available', 'Genre']

## Data Science

### Univariate Analysis
Measure of Central Tendency - applicable for quantitative columns
Measure of Location of Data - applicable for quantitative columns
IQR - Inter Quartile Range

### Bivariate Analysis
Covariance
Correlation

In [24]:
import numpy as np # numpy library mostly used for calculation/statistical purpose

In [25]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__doc__',
 '__file__',
 '__git_revision__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_distributor_init',
 '_globals',
 '_mat',
 '_pytesttester',
 'abs',
 'absolute',
 'absolute_import',
 'add',
 'add_docstring',
 'add_newdoc',
 'add_newdoc_ufunc',
 'alen',
 'all',
 'allclose',
 'alltrue',
 'amax',
 'amin',
 'angle',
 'any',
 'append',
 'apply_along_axis',
 'apply_over_axes',
 'arange',
 'arccos',
 'arccosh',
 'arcsin',
 'arcsinh',
 'arctan',
 'arctan2',
 'arctanh',
 'argmax',
 'argmin',
 'argpartition',
 'argsort',
 'argwhere',
 'around',
 'array',
 'array2string',
 'array_equal',
 'array_equiv',
 'array_repr',
 'array_split',
 'array_str',
 'asanyarray',
 'asarray',
 'asarray_chkfinite',
 'ascontiguousarray',
 'asfarray',
 'asfortranarray',
 'asmatrix',
 'asscalar',
 'atleast_1d',
 'atleast_2d',
 'atleast_3d',
 'average',
 'bartlett',
 'base_repr',
 'binary_repr',
 'bincount',
 'bitwise_and',
 'bitwise_not',
 'bitwise_or',
 'bitwise_xor',
 'blackman',
 'block',
 'bmat',
 'bool',
 'bool8',
 'bool_',
 'broadcast',
 'broadcast_arrays',
 'broadcast_to',
 'busday_count',
 'busday_offset',
 'busdaycalendar',
 'byte',
 'byte_bounds',
 'bytes0',
 'bytes_',
 'c_',
 'can_cast',
 'cast',
 'cbrt',
 'cdouble',
 'ceil',
 'cfloat',
 'char',
 'character',
 'chararray',
 'choose',
 'clip',
 'clongdouble',
 'clongfloat',
 'column_stack',
 'common_type',
 'compare_chararrays',
 'compat',
 'complex',
 'complex128',
 'complex64',
 'complex_',
 'complexfloating',
 'compress',
 'concatenate',
 'conj',
 'conjugate',
 'convolve',
 'copy',
 'copysign',
 'copyto',
 'core',
 'corrcoef',
 'correlate',
 'cos',
 'cosh',
 'count_nonzero',
 'cov',
 'cross',
 'csingle',
 'ctypeslib',
 'cumprod',
 'cumproduct',
 'cumsum',
 'datetime64',
 'datetime_as_string',
 'datetime_data',
 'deg2rad',
 'degrees',
 'delete',
 'deprecate',
 'deprecate_with_doc',
 'diag',
 'diag_indices',
 'diag_indices_from',
 'diagflat',
 'diagonal',
 'diff',
 'digitize',
 'disp',
 'divide',
 'division',
 'divmod',
 'dot',
 'double',
 'dsplit',
 'dstack',
 'dtype',
 'e',
 'ediff1d',
 'einsum',
 'einsum_path',
 'emath',
 'empty',
 'empty_like',
 'equal',
 'errstate',
 'euler_gamma',
 'exp',
 'exp2',
 'expand_dims',
 'expm1',
 'extract',
 'eye',
 'fabs',
 'fastCopyAndTranspose',
 'fft',
 'fill_diagonal',
 'find_common_type',
 'finfo',
 'fix',
 'flatiter',
 'flatnonzero',
 'flexible',
 'flip',
 'fliplr',
 'flipud',
 'float',
 'float16',
 'float32',
 'float64',
 'float_',
 'float_power',
 'floating',
 'floor',
 'floor_divide',
 'fmax',
 'fmin',
 'fmod',
 'format_float_positional',
 'format_float_scientific',
 'format_parser',
 'frexp',
 'frombuffer',
 'fromfile',
 'fromfunction',
 'fromiter',
 'frompyfunc',
 'fromregex',
 'fromstring',
 'full',
 'full_like',
 'fv',
 'gcd',
 'generic',
 'genfromtxt',
 'geomspace',
 'get_array_wrap',
 'get_include',
 'get_printoptions',
 'getbufsize',
 'geterr',
 'geterrcall',
 'geterrobj',
 'gradient',
 'greater',
 'greater_equal',
 'half',
 'hamming',
 'hanning',
 'heaviside',
 'histogram',
 'histogram2d',
 'histogram_bin_edges',
 'histogramdd',
 'hsplit',
 'hstack',
 'hypot',
 'i0',
 'identity',
 'iinfo',
 'imag',
 'in1d',
 'index_exp',
 'indices',
 'inexact',
 'inf',
 'info',
 'infty',
 'inner',
 'insert',
 'int',
 'int0',
 'int16',
 'int32',
 'int64',
 'int8',
 'int_',
 'int_asbuffer',
 'intc',
 'integer',
 'interp',
 'intersect1d',
 'intp',
 'invert',
 'ipmt',
 'irr',
 'is_busday',
 'isclose',
 'iscomplex',
 'iscomplexobj',
 'isfinite',
 'isfortran',
 'isin',
 'isinf',
 'isnan',
 'isnat',
 'isneginf',
 'isposinf',
 'isreal',
 'isrealobj',
 'isscalar',
 'issctype',
 'issubclass_',
 'issubdtype',
 'issubsctype',
 'iterable',
 'ix_',
 'kaiser',
 'kron',
 'lcm',
 'ldexp',
 'left_shift',
 'less',
 'less_equal',
 'lexsort',
 'lib',
 'linalg',
 'linspace',
 'little_endian',
 'load',
 'loads',
 'loadtxt',
 'log',
 'log10',
 'log1p',
 'log2',
 'logaddexp',
 'logaddexp2',
 'logical_and',
 'logical_not',
 'logical_or',
 'logical_xor',
 'logspace',
 'long',
 'longcomplex',
 'longdouble',
 'longfloat',
 'longlong',
 'lookfor',
 'ma',
 'mafromtxt',
 'mask_indices',
 'mat',
 'math',
 'matmul',
 'matrix',
 'matrixlib',
 'max',
 'maximum',
 'maximum_sctype',
 'may_share_memory',
 'mean',
 'median',
 'memmap',
 'meshgrid',
 'mgrid',
 'min',
 'min_scalar_type',
 'minimum',
 'mintypecode',
 'mirr',
 'mod',
 'modf',
 'moveaxis',
 'msort',
 'multiply',
 'nan',
 'nan_to_num',
 'nanargmax',
 'nanargmin',
 'nancumprod',
 'nancumsum',
 'nanmax',
 'nanmean',
 'nanmedian',
 'nanmin',
 'nanpercentile',
 'nanprod',
 'nanquantile',
 'nanstd',
 'nansum',
 'nanvar',
 'nbytes',
 'ndarray',
 'ndenumerate',
 'ndfromtxt',
 'ndim',
 'ndindex',
 'nditer',
 'negative',
 'nested_iters',
 'newaxis',
 'nextafter',
 'nonzero',
 'not_equal',
 'nper',
 'npv',
 'numarray',
 'number',
 'obj2sctype',
 'object',
 'object0',
 'object_',
 'ogrid',
 'oldnumeric',
 'ones',
 'ones_like',
 'outer',
 'packbits',
 'pad',
 'partition',
 'percentile',
 'pi',
 'piecewise',
 'place',
 'pmt',
 'poly',
 'poly1d',
 'polyadd',
 'polyder',
 'polydiv',
 'polyfit',
 'polyint',
 'polymul',
 'polynomial',
 'polysub',
 'polyval',
 'positive',
 'power',
 'ppmt',
 'print_function',
 'printoptions',
 'prod',
 'product',
 'promote_types',
 'ptp',
 'put',
 'put_along_axis',
 'putmask',
 'pv',
 'quantile',
 'r_',
 'rad2deg',
 'radians',
 'random',
 'rank',
 'rate',
 'ravel',
 'ravel_multi_index',
 'real',
 'real_if_close',
 'rec',
 'recarray',
 'recfromcsv',
 'recfromtxt',
 'reciprocal',
 'record',
 'remainder',
 'repeat',
 'require',
 'reshape',
 'resize',
 'result_type',
 'right_shift',
 'rint',
 'roll',
 'rollaxis',
 'roots',
 'rot90',
 'round',
 'round_',
 'row_stack',
 's_',
 'safe_eval',
 'save',
 'savetxt',
 'savez',
 'savez_compressed',
 'sctype2char',
 'sctypeDict',
 'sctypeNA',
 'sctypes',
 'searchsorted',
 'select',
 'set_numeric_ops',
 'set_printoptions',
 'set_string_function',
 'setbufsize',
 'setdiff1d',
 'seterr',
 'seterrcall',
 'seterrobj',
 'setxor1d',
 'shape',
 'shares_memory',
 'short',
 'show_config',
 'sign',
 'signbit',
 'signedinteger',
 'sin',
 'sinc',
 'single',
 'singlecomplex',
 'sinh',
 'size',
 'sometrue',
 'sort',
 'sort_complex',
 'source',
 'spacing',
 'split',
 'sqrt',
 'square',
 'squeeze',
 'stack',
 'std',
 'str',
 'str0',
 'str_',
 'string_',
 'subtract',
 'sum',
 'swapaxes',
 'sys',
 'take',
 'take_along_axis',
 'tan',
 'tanh',
 'tensordot',
 'test',
 'testing',
 'tile',
 'timedelta64',
 'trace',
 'tracemalloc_domain',
 'transpose',
 'trapz',
 'tri',
 'tril',
 'tril_indices',
 'tril_indices_from',
 'trim_zeros',
 'triu',
 'triu_indices',
 'triu_indices_from',
 'true_divide',
 'trunc',
 'typeDict',
 'typeNA',
 'typecodes',
 'typename',
 'ubyte',
 'ufunc',
 'uint',
 'uint0',
 'uint16',
 'uint32',
 'uint64',
 'uint8',
 'uintc',
 'uintp',
 'ulonglong',
 'unicode',
 'unicode_',
 'union1d',
 'unique',
 'unpackbits',
 'unravel_index',
 'unsignedinteger',
 'unwrap',
 'ushort',
 'vander',
 'var',
 'vdot',
 'vectorize',
 'version',
 'void',
 'void0',
 'vsplit',
 'vstack',
 'warnings',
 'where',
 'who',
 'zeros',
 'zeros_like']

In [26]:
dataset.describe() # inbuild function to achieve basic DS

,Marketing expense,Production expense,Multiplex coverage,Budget,Movie_length,Lead_ Actor_Rating,Lead_Actress_rating,Director_rating,Producer_rating,Critic_rating,Trailer_views,Time_taken,Twitter_hastags,Avg_age_actors,Num_multiplex,Collection,Start_Tech_Oscar
count,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000
mean,92.270471,77.273557,0.445305,34911.144022,142.074901,8.014002,8.185613,8.019664,8.190514,7.810870,449860.715415,153.658893,260.832095,39.181818,545.043478,45057.707510,0.545455
std,172.030902,13.720706,0.115878,3903.038232,28.148861,1.054266,1.054290,1.059899,1.049601,0.659699,68917.763145,39.125416,104.779133,12.513697,106.332889,18364.351764,0.498422
min,20.126400,55.920000,0.129000,19781.355000,76.400000,3.840000,4.035000,3.840000,4.030000,6.600000,212912.000000,0.000000,201.152000,3.000000,333.000000,10000.000000,0.000000
25%,21.640900,65.380000,0.376000,32693.952500,118.525000,7.316250,7.503750,7.296250,7.507500,7.200000,409128.000000,129.570000,223.796000,28.000000,465.000000,34050.000000,0.000000
50%,25.130200,74.380000,0.462000,34488.217500,151.000000,8.307500,8.495000,8.312500,8.465000,7.960000,462460.000000,158.980000,254.400000,39.000000,535.500000,42400.000000,1.000000
75%,93.541650,91.200000,0.551000,36793.542500,167.575000,8.865000,9.030000,8.883750,9.030000,8.260000,500247.500000,181.520000,283.416000,50.000000,614.750000,50000.000000,1.000000
max,1799.524000,110.480000,0.615000,48772.900000,173.500000,9.435000,9.540000,9.425000,9.635000,9.400000,567784.000000,217.520000,2022.400000,60.000000,868.000000,100000.000000,1.000000

In [27]:
#Detailed Data Analysis 

MLD=pd.DataFrame(index=["Mean","Median","Mode","Min","Q1:25%","Q2:50%","Q3:75%","99%","Max","Q4:100%","IQR","1.5Rule","Lesser Outlier","Greater Outlier","Minimum","Maximum"],columns=Quan) # Table Creation with proper row and columns
for columnName in Quan:
    MLD[columnName]["Mean"]=dataset[columnName].mean() # considering outlier => finding avg for the given set
    MLD[columnName]["Median"]=dataset[columnName].median() # not considering outlier => finding mid term for the given set
    MLD[columnName]["Mode"]=dataset[columnName].mode()[0] # repeated value for the given set
    #From here MLD - PERCENTILE coding starts
    MLD[columnName]["Min"]=np.percentile(dataset[columnName],0)
    MLD[columnName]["Q1:25%"]=np.percentile(dataset[columnName],25)
    MLD[columnName]["Q2:50%"]=np.percentile(dataset[columnName],50)
    MLD[columnName]["Q3:75%"]=np.percentile(dataset[columnName],75)
    MLD[columnName]["99%"]=np.percentile(dataset[columnName],99)
    MLD[columnName]["Max"]=np.percentile(dataset[columnName],100)
    #From here IQR, 1.5rule, Lesser Outlier and Greater Outlier coding starts. 
    #IQR = Q3-Q1
    MLD[columnName]["IQR"]=MLD[columnName]["Q3:75%"]-MLD[columnName]["Q1:25%"]
    #1.5Rule = 1.5*IQR
    MLD[columnName]["1.5Rule"]=1.5*MLD[columnName]["IQR"]
    #Lesser Outlier = Q1-1.5*IQR
    MLD[columnName]["Lesser Outlier"]=MLD[columnName]["Q1:25%"]-MLD[columnName]["1.5Rule"]
    #Greater Outlier = Q3+1.5*IQR
    MLD[columnName]["Greater Outlier"]=MLD[columnName]["Q3:75%"]+MLD[columnName]["1.5Rule"]
    #Minimum
    MLD[columnName]["Minimum"]=dataset[columnName].min()
    #Maximum
    MLD[columnName]["Maximum"]=dataset[columnName].max()

In [28]:
MLD

,Marketing expense,Production expense,Multiplex coverage,Budget,Movie_length,Lead_ Actor_Rating,Lead_Actress_rating,Director_rating,Producer_rating,Critic_rating,Trailer_views,Time_taken,Twitter_hastags,Avg_age_actors,Num_multiplex,Collection,Start_Tech_Oscar
Mean,92.2705,77.2736,0.445305,34911.1,142.075,8.014,8.18561,8.01966,8.19051,7.81087,449861,153.659,260.832,39.1818,545.043,45057.7,0.545455
Median,25.1302,74.38,0.462,34488.2,151,8.3075,8.495,8.3125,8.465,7.96,462460,158.98,254.4,39,535.5,42400,1
Mode,20.3002,91.2,0.462,31735.7,173.5,9.02,9.23,8.815,9.095,7.96,474433,0,268,57,470,100000,1
Min,20.1264,55.92,0.129,19781.4,76.4,3.84,4.035,3.84,4.03,6.6,212912,0,201.152,3,333,10000,0
Q1:25%,21.6409,65.38,0.376,32694,118.525,7.31625,7.50375,7.29625,7.5075,7.2,409128,129.57,223.796,28,465,34050,0
Q2:50%,25.1302,74.38,0.462,34488.2,151,8.3075,8.495,8.3125,8.465,7.96,462460,158.98,254.4,39,535.5,42400,1
Q3:75%,93.5417,91.2,0.551,36793.5,167.575,8.865,9.03,8.88375,9.03,8.26,500248,181.52,283.416,50,614.75,50000,1
99%,847.407,106.3,0.602,46300.9,173.5,9.27,9.48,9.3145,9.5045,9.394,560792,212.402,307.99,60,829.8,100000,1
Max,1799.52,110.48,0.615,48772.9,173.5,9.435,9.54,9.425,9.635,9.4,567784,217.52,2022.4,60,868,100000,1
Q4:100%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
IQR,71.9008,25.82,0.175,4099.59,49.05,1.54875,1.52625,1.5875,1.5225,1.06,91119.5,51.95,59.62,22,149.75,15950,1
1.5Rule,107.851,38.73,0.2625,6149.38,73.575,2.32313,2.28937,2.38125,2.28375,1.59,136679,77.925,89.43,33,224.625,23925,1.5
Lesser Outlier,-86.2102,26.65,0.1135,26544.6,44.95,4.99313,5.21438,4.915,5.22375,5.61,272449,51.645,134.366,-5,240.375,10125,-1.5
Greater Outlier,201.393,129.93,0.8135,42942.9,241.15,11.1881,11.3194,11.265,11.3137,9.85,636927,259.445,372.846,83,839.375,73925,2.5
Minimum,20.1264,55.92,0.129,19781.4,76.4,3.84,4.035,3.84,4.03,6.6,212912,0,201.152,3,333,10000,0
Maximum,1799.52,110.48,0.615,48772.9,173.5,9.435,9.54,9.425,9.635,9.4,567784,217.52,2022.4,60,868,100000,1

# Finding Outlier Columns

In [29]:
#splitting lesser outlier columns and greater outlier columns in two different lists
lesser=[]
greater=[]

In [30]:
for columnName in Quan:
    if MLD[columnName]["Minimum"] < MLD[columnName]["Lesser Outlier"]: #logic to find lesser outlier columns in the dataframe
        lesser.append(columnName)
    if MLD[columnName]["Maximum"] > MLD[columnName]["Greater Outlier"]:  #logic to find greater outlier columns in the dataframe
        greater.append(columnName)

In [31]:
lesser

['Budget',
 'Lead_ Actor_Rating',
 'Lead_Actress_rating',
 'Director_rating',
 'Producer_rating',
 'Trailer_views',
 'Time_taken',
 'Collection']

In [32]:
greater

['Marketing expense',
 'Budget',
 'Twitter_hastags',
 'Num_multiplex',
 'Collection']

# Replacing Outliers

In [33]:
for columnName in lesser:
    dataset[columnName][dataset[columnName]<MLD[columnName]["Lesser Outlier"]]=MLD[columnName]["Lesser Outlier"]
for columnName in greater:
    dataset[columnName][dataset[columnName]>MLD[columnName]["Greater Outlier"]]=MLD[columnName]["Greater Outlier"]

C:\Users\krish\Anaconda3\envs\krish_virtual\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\krish\Anaconda3\envs\krish_virtual\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\krish\Anaconda3\envs\krish_virtual\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.

In [34]:
# Forming a DataFrame Post to Outlier Replacement
MLD=pd.DataFrame(index=["Mean","Median","Mode","Min","Q1:25%","Q2:50%","Q3:75%","Q4:100%","IQR","1.5Rule","Lesser Outlier","Greater Outlier","Minimum","Maximum"],
                 columns=Quan) # Table Creation with proper row and columns
for columnName in Quan:
    MLD[columnName]["Mean"]=dataset[columnName].mean() # considering outlier => finding avg for the given set
    MLD[columnName]["Median"]=dataset[columnName].median() # not considering outlier => finding mid term for the given set
    MLD[columnName]["Mode"]=dataset[columnName].mode()[0] # repeated value for the given set
    #From here MLD - PERCENTILE coding starts
    MLD[columnName]["Min"]= dataset.describe()[columnName]["min"] #np.percentile(dataset[columnName],0)
    MLD[columnName]["Q1:25%"]= dataset.describe()[columnName]["25%"] #np.percentile(dataset[columnName],25)
    MLD[columnName]["Q2:50%"]= dataset.describe()[columnName]["50%"] #np.percentile(dataset[columnName],50)
    MLD[columnName]["Q3:75%"]= dataset.describe()[columnName]["75%"] #np.percentile(dataset[columnName],75)
    MLD[columnName]["Q4:100%"]= dataset.describe()[columnName]["max"] #np.percentile(dataset[columnName],100)
    #From here IQR, 1.5rule, Lesser Outlier and Greater Outlier coding starts. 
    #IQR = Q3-Q1
    MLD[columnName]["IQR"]=MLD[columnName]["Q3:75%"]-MLD[columnName]["Q1:25%"]
    #1.5Rule = 1.5*IQR
    MLD[columnName]["1.5Rule"]=1.5*MLD[columnName]["IQR"]
    #Lesser Outlier = Q1-1.5*IQR
    MLD[columnName]["Lesser Outlier"]=MLD[columnName]["Q1:25%"]-MLD[columnName]["1.5Rule"]
    #Greater Outlier = Q3+1.5*IQR
    MLD[columnName]["Greater Outlier"]=MLD[columnName]["Q3:75%"]+MLD[columnName]["1.5Rule"]
    #Minimum
    MLD[columnName]["Minimum"]=dataset[columnName].min()
    #Maximum
    MLD[columnName]["Maximum"]=dataset[columnName].max()

In [35]:
MLD

,Marketing expense,Production expense,Multiplex coverage,Budget,Movie_length,Lead_ Actor_Rating,Lead_Actress_rating,Director_rating,Producer_rating,Critic_rating,Trailer_views,Time_taken,Twitter_hastags,Avg_age_actors,Num_multiplex,Collection,Start_Tech_Oscar
Mean,64.5006,77.2736,0.445305,34859.4,142.075,8.01958,8.19147,8.02428,8.19656,7.81087,450379,155.088,255.103,39.1818,544.95,43746.4,0.545455
Median,25.1302,74.38,0.462,34488.2,151,8.3075,8.495,8.3125,8.465,7.96,462460,158.98,254.4,39,535.5,42400,1
Mode,201.393,91.2,0.462,42942.9,173.5,4.99313,9.23,4.915,9.095,7.96,272449,51.645,268,57,470,73925,1
Min,20.1264,55.92,0.129,26544.6,76.4,4.99313,5.21438,4.915,5.22375,6.6,272449,51.645,201.152,3,333,10125,0
Q1:25%,21.6409,65.38,0.376,32694,118.525,7.31625,7.50375,7.29625,7.5075,7.2,409128,129.57,223.796,28,465,34050,0
Q2:50%,25.1302,74.38,0.462,34488.2,151,8.3075,8.495,8.3125,8.465,7.96,462460,158.98,254.4,39,535.5,42400,1
Q3:75%,93.5417,91.2,0.551,36793.5,167.575,8.865,9.03,8.88375,9.03,8.26,500248,181.52,283.416,50,614.75,50000,1
Q4:100%,201.393,110.48,0.615,42942.9,173.5,9.435,9.54,9.425,9.635,9.4,567784,217.52,372.846,60,839.375,73925,1
IQR,71.9008,25.82,0.175,4099.59,49.05,1.54875,1.52625,1.5875,1.5225,1.06,91119.5,51.95,59.62,22,149.75,15950,1
1.5Rule,107.851,38.73,0.2625,6149.38,73.575,2.32313,2.28937,2.38125,2.28375,1.59,136679,77.925,89.43,33,224.625,23925,1.5
Lesser Outlier,-86.2102,26.65,0.1135,26544.6,44.95,4.99313,5.21438,4.915,5.22375,5.61,272449,51.645,134.366,-5,240.375,10125,-1.5
Greater Outlier,201.393,129.93,0.8135,42942.9,241.15,11.1881,11.3194,11.265,11.3137,9.85,636927,259.445,372.846,83,839.375,73925,2.5
Minimum,20.1264,55.92,0.129,26544.6,76.4,4.99313,5.21438,4.915,5.22375,6.6,272449,51.645,201.152,3,333,10125,0
Maximum,201.393,110.48,0.615,42942.9,173.5,9.435,9.54,9.425,9.635,9.4,567784,217.52,372.846,60,839.375,73925,1

In [36]:
# Confirming no outlier exists
lesser1=[]
greater1=[]
for columnName in Quan:
    if MLD[columnName]["Minimum"] < MLD[columnName]["Lesser Outlier"]: #logic to find lesser outlier columns in the dataframe
        lesser1.append(columnName)
    if MLD[columnName]["Maximum"] > MLD[columnName]["Greater Outlier"]:  #logic to find greater outlier columns in the dataframe
        greater1.append(columnName)

In [37]:
lesser1

[]

In [38]:
greater1

[]

# Bivariate Analysis

In [39]:
dataset.cov() #automatically doing covariance between the quantitative columns

,Marketing expense,Production expense,Multiplex coverage,Budget,Movie_length,Lead_ Actor_Rating,Lead_Actress_rating,Director_rating,Producer_rating,Critic_rating,Trailer_views,Time_taken,Twitter_hastags,Avg_age_actors,Num_multiplex,Collection,Start_Tech_Oscar
Marketing expense,4.391324e+03,572.192782,-5.094256,-6.033336e+04,9.680205e+02,38.231386,38.095560,38.479951,37.467497,-10.763722,-2.600531e+06,-61.395939,184.869715,66.698488,4.244957e+03,-5.447206e+05,0.749354
Production expense,5.721928e+02,188.257770,-1.214147,-1.963258e+04,2.490278e+02,10.116102,10.132500,10.204324,10.052574,-2.277047,-5.520199e+05,5.953418,-9.096939,9.582362,1.030713e+03,-1.171448e+05,-0.166895
Multiplex coverage,-5.094256e+00,-1.214147,0.013428,1.307990e+02,-2.385927e+00,-0.093094,-0.093194,-0.093802,-0.092159,0.011127,4.590968e+03,0.230051,-0.073906,-0.133556,-1.125061e+01,8.952289e+02,-0.000232
Budget,-6.033336e+04,-19632.581233,130.798960,1.225698e+07,-2.550327e+04,-825.711713,-812.613544,-806.119309,-808.889758,544.496399,1.473058e+08,7551.641753,-1414.685491,-2981.266500,-1.130266e+05,3.712656e+07,-58.098500
Movie_length,9.680205e+02,249.027806,-2.385927,-2.550327e+04,7.923584e+02,21.945880,21.919538,22.107399,21.821550,-4.045057,-1.127523e+06,-41.162861,11.191483,26.488137,2.015380e+03,-1.965510e+05,0.228569
Lead_ Actor_Rating,3.823139e+01,10.116102,-0.093094,-8.257117e+02,2.194588e+01,1.073678,1.070662,1.080049,1.060825,-0.117563,-3.474681e+04,0.441113,0.883904,0.508799,7.848990e+01,-5.256730e+03,-0.016015
Lead_Actress_rating,3.809556e+01,10.132500,-0.093194,-8.126135e+02,2.191954e+01,1.070662,1.072304,1.079712,1.060083,-0.114775,-3.454360e+04,0.507846,0.778601,0.527353,7.868124e+01,-5.235324e+03,-0.018540
Director_rating,3.847995e+01,10.204324,-0.093802,-8.061193e+02,2.210740e+01,1.080049,1.079712,1.091547,1.069669,-0.115396,-3.470572e+04,0.459537,0.742481,0.567379,7.936975e+01,-5.214586e+03,-0.016794
Producer_rating,3.746750e+01,10.052574,-0.092159,-8.088898e+02,2.182155e+01,1.060825,1.060083,1.069669,1.061134,-0.114962,-3.437651e+04,0.256868,0.575030,0.452471,7.777290e+01,-5.180845e+03,-0.020062
Critic_rating,-1.076372e+01,-2.277047,0.011127,5.444964e+02,-4.045057e+00,-0.117563,-0.114775,-0.115396,-0.114962,0.435203,1.030890e+04,0.583765,-0.792695,-0.411089,-9.136006e+00,3.421002e+03,-0.000356
Trailer_views,-2.600531e+06,-552019.898337,4590.967844,1.473058e+08,-1.127523e+06,-34746.807033,-34543.598680,-34705.718124,-34376.505681,10308.898267,4.542606e+09,230663.273409,-91856.597152,-41374.045455,-3.934809e+06,8.009771e+08,-2370.648740
Time_taken,-6.139594e+01,5.953418,0.230051,7.551642e+03,-4.116286e+01,0.441113,0.507846,0.459537,0.256868,0.583765,2.306633e+05,1162.694707,1.859138,38.821518,-2.796418e+02,5.712309e+04,-0.877623
Twitter_hastags,1.848697e+02,-9.096939,-0.073906,-1.414685e+03,1.119148e+01,0.883904,0.778601,0.742481,0.575030,-0.792695,-9.185660e+04,1.859138,1179.647343,22.708031,1.376727e+02,-1.198209e+03,1.429207
Avg_age_actors,6.669849e+01,9.582362,-0.133556,-2.981266e+03,2.648814e+01,0.508799,0.527353,0.567379,0.452471,-0.411089,-4.137405e+04,38.821518,22.708031,156.592619,1.045508e+02,-8.846521e+03,0.253105
Num_multiplex,4.244957e+03,1030.712863,-11.250614,-1.130266e+05,2.015380e+03,78.489904,78.681242,79.369751,77.772898,-9.136006,-3.934809e+06,-279.641764,137.672656,104.550765,1.124933e+04,-7.556624e+05,-0.229140
Collection,-5.447206e+05,-117144.804471,895.228924,3.712656e+07,-1.965510e+05,-5256.730430,-5235.323724,-5214.586023,-5180.845233,3421.001657,8.009771e+08,57123.086627,-1198.208903,-8846.521152,-7.556624e+05,2.301117e+08,872.565257
Start_Tech_Oscar,7.493544e-01,-0.166895,-0.000232,-5.809850e+01,2.285689e-01,-0.016015,-0.018540,-0.016794,-0.020062,-0.000356,-2.370649e+03,-0.877623,1.429207,0.253105,-2.291404e-01,8.725653e+02,0.248425

In [40]:
dataset.corr() #automatically doing correlation between the quantitative columns

,Marketing expense,Production expense,Multiplex coverage,Budget,Movie_length,Lead_ Actor_Rating,Lead_Actress_rating,Director_rating,Producer_rating,Critic_rating,Trailer_views,Time_taken,Twitter_hastags,Avg_age_actors,Num_multiplex,Collection,Start_Tech_Oscar
Marketing expense,1.000000,0.629315,-0.663412,-0.260057,0.518951,0.556782,0.555159,0.555796,0.548873,-0.246217,-0.582253,-0.027171,0.081225,0.080433,0.603966,-0.541884,0.022688
Production expense,0.629315,1.000000,-0.763651,-0.408704,0.644779,0.711541,0.713151,0.711847,0.711239,-0.251565,-0.596933,0.012725,-0.019304,0.055810,0.708269,-0.562830,-0.024404
Multiplex coverage,-0.663412,-0.763651,1.000000,0.322413,-0.731470,-0.775323,-0.776661,-0.774805,-0.772061,0.145555,0.587830,0.058222,-0.018570,-0.092104,-0.915405,0.509290,-0.004017
Budget,-0.260057,-0.408704,0.322413,1.000000,-0.258788,-0.227614,-0.224147,-0.220387,-0.224291,0.235753,0.624274,0.063258,-0.011765,-0.068049,-0.304387,0.699075,-0.033295
Movie_length,0.518951,0.644779,-0.731470,-0.258788,1.000000,0.752411,0.751989,0.751719,0.752557,-0.217830,-0.594309,-0.042886,0.011576,0.075198,0.675045,-0.460304,0.016291
Lead_ Actor_Rating,0.556782,0.711541,-0.775323,-0.227614,0.752411,1.000000,0.997830,0.997666,0.993851,-0.171983,-0.497537,0.012485,0.024837,0.039239,0.714190,-0.334433,-0.031009
Lead_Actress_rating,0.555159,0.713151,-0.776661,-0.224147,0.751989,0.997830,1.000000,0.997994,0.993793,-0.168012,-0.494944,0.014383,0.021892,0.040696,0.716389,-0.333285,-0.035922
Director_rating,0.555796,0.711847,-0.774805,-0.220387,0.751719,0.997666,0.997994,1.000000,0.993901,-0.167427,-0.492864,0.012899,0.020691,0.043398,0.716260,-0.329025,-0.032250
Producer_rating,0.548873,0.711239,-0.772061,-0.224291,0.752557,0.993851,0.993793,0.993901,1.000000,-0.169170,-0.495135,0.007313,0.016253,0.035101,0.711836,-0.331548,-0.039075
Critic_rating,-0.246217,-0.251565,0.145555,0.235753,-0.217830,-0.171983,-0.168012,-0.167427,-0.169170,1.000000,0.231854,0.025951,-0.034985,-0.049797,-0.130571,0.341852,-0.001084
Trailer_views,-0.582253,-0.596933,0.587830,0.624274,-0.594309,-0.497537,-0.494944,-0.492864,-0.495135,0.231854,1.000000,0.100367,-0.039681,-0.049056,-0.550437,0.783426,-0.070570
Time_taken,-0.027171,0.012725,0.058222,0.063258,-0.042886,0.012485,0.014383,0.012899,0.007313,0.025951,0.100367,1.000000,0.001587,0.090982,-0.077323,0.110436,-0.051639
Twitter_hastags,0.081225,-0.019304,-0.018570,-0.011765,0.011576,0.024837,0.021892,0.020691,0.016253,-0.034985,-0.039681,0.001587,1.000000,0.052835,0.037793,-0.002300,0.083488
Avg_age_actors,0.080433,0.055810,-0.092104,-0.068049,0.075198,0.039239,0.040696,0.043398,0.035101,-0.049797,-0.049056,0.090982,0.052835,1.000000,0.078773,-0.046603,0.040581
Num_multiplex,0.603966,0.708269,-0.915405,-0.304387,0.675045,0.714190,0.716389,0.716260,0.711836,-0.130571,-0.550437,-0.077323,0.037793,0.078773,1.000000,-0.469673,-0.004335
Collection,-0.541884,-0.562830,0.509290,0.699075,-0.460304,-0.334433,-0.333285,-0.329025,-0.331548,0.341852,0.783426,0.110436,-0.002300,-0.046603,-0.469673,1.000000,0.115407
Start_Tech_Oscar,0.022688,-0.024404,-0.004017,-0.033295,0.016291,-0.031009,-0.035922,-0.032250,-0.039075,-0.001084,-0.070570,-0.051639,0.083488,0.040581,-0.004335,0.115407,1.000000